[package]
name = "lpm"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-ini = { git = "https://github.com/zonyitoo/rust-ini/", rev="ecad660a05960155f208bfc701d06de92ff8a7b7" }
clap = { version = "4.5.4", features = ["derive"] }
tabled = "0.15.0"
users = "0.11.0"
