[package]
name = "lpm"
version = "0.1.0"
edition = "2021"

[dependencies]
# systemctl = "0.3.1"
rust-ini = { git = "https://github.com/zonyitoo/rust-ini/", rev="ecad660a05960155f208bfc701d06de92ff8a7b7" }
is-root = "0.1.3"
# dbus = "0.9.7"
clap = { version = "4.5.4", features = ["derive"] }
